name: TerminalGui-$(SourceBranchName)$(Rev:.r)

stages:
- stage: BuildAndTest
  displayName: 'Build and test'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - task: DotNetCoreCLI@2
          displayName: 'Publish'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'RpiProbeLogger.TerminalGui/RpiProbeLogger.TerminalGui.csproj'
            arguments: '--self-contained -r linux-arm -f net6.0 -c Release'
- stage: DeployTerminalGui
  displayName: 'TerminalGui'
  jobs:
    - deployment: TerminalGui
      environment: Home