name: RpiProbeLogger-$(SourceBranchName)$(Rev:.r)

trigger:
  tags:
    include:
      - release-*
  paths:
    include:
      - RpiProbeLogger
      - RpiProbeLogger.BusModels
      - ReportCsvHandlerTests
      - SenseServiceTests
      - TemperServiceTests
      - ReportServiceTests

stages:
- stage: BuildAndTest
  displayName: 'Build and test'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'RpiProbeLogger/RpiProbeLogger.csproj'
            arguments: '--self-contained -r linux-arm -f net6.0 -c Release -o $(Build.ArtifactStagingDirectory)'
- stage: DeployRpiProbeLoggerHome
  displayName: 'Deploy Home'
  jobs:
    - deployment: RpiProbeLoggerHome
      environment: Home
- stage: DeployRpiProbeLoggerVostok
  displayName: 'Deploy Vostok'
  dependsOn: DeployRpiProbeLoggerHome
  jobs:
    - deployment: RpiProbeLoggerVostok
      environment: Vostok
