name: $(SourceBranchName)$(Rev:.r)

#trigger:
#- master

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Publish RpiProbeLogger'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'RpiProbeLogger/RpiProbeLogger.csproj'
          arguments: '--self-contained -r linux-arm -f net6.0 -c Release'
      - task: DotNetCoreCLI@2
        displayName: 'Publish TerminalGui'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'RpiProbeLogger.TerminalGui/RpiProbeLogger.TerminalGui.csproj'
          arguments: '--self-contained -r linux-arm -f net6.0 -c Release'