name: $(SourceBranchName)$(Rev:.r)

trigger:
  tags:
    include:
      - release-*
  paths:
    include:
      - RpiProbeLogger
      - RpiProbeLogger.BusModels
      - ReportCsvHandlerTests
      - SenseServiceTests
      - TemperServiceTests
      - ReportServiceTests

stages:
- stage: BuildAndTest
  displayName: 'Build and test'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: 'test'
            projects: '**/*Tests.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'RpiProbeLogger/RpiProbeLogger.csproj'
            arguments: '--self-contained -r linux-arm -f net6.0 -c Release'
        - publish: $(System.DefaultWorkingDirectory)/RpiProbeLogger/bin/Release/net6.0/linux-arm
          displayName: 'Publish artifacts'
          artifact: RpiProbeLogger
- stage: DeployRpiProbeLoggerHome
  displayName: 'Deploy Home'
  jobs:
    - deployment: RpiProbeLoggerHome
      environment:
        name: Home
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
              - task: CopyFiles@2
                displayName: 'Copy files'
                inputs:
                  SourceFolder: '$(Pipeline.Workspace)/RpiProbeLogger'
                  Contents: '**'
                  TargetFolder: '$(HOME)/RpiProbeLogger'
                  CleanTargetFolder: true
              - script: chmod +x $(HOME)/RpiProbeLogger/RpiProbeLogger
                displayName: 'Make executable'
              - script: sudo systemctl enable $(HOME)/RpiProbeLogger/probelogger.service
                displayName: 'Enable logger service'
              - script: sudo systemctl start probelogger
                displayName: 'Start logger service'
          on:
            success:
              steps:
                - script: sudo systemctl stop probelogger
                  displayName: 'Stop logger service'
                - script: sudo systemctl disable probelogger
                  displayName: 'Disable logger service'
              
- stage: DeployRpiProbeLoggerVostok
  displayName: 'Deploy Vostok'
  dependsOn: DeployRpiProbeLoggerHome
  jobs:
    - deployment: RpiProbeLoggerVostok
      environment: Vostok
